package com.example.mp;

import androidx.appcompat.app.AppCompatActivity;
import android.content.Context;
import android.content.Intent;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.media.MediaPlayer;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

public class MainActivity extends AppCompatActivity {
    public static String user;
    public EditText User, Pass;
    SQLiteDatabase database;
    String pass,first,last,age,birth;
    Button Login;
    Intent intent;
    MediaPlayer music;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        music = MediaPlayer.create(MainActivity.this,R.raw.bg_music);
        music.start();
        database = openOrCreateDatabase("USER", Context.MODE_PRIVATE, null);
        database.execSQL("CREATE TABLE IF NOT EXISTS USER_INFO(USER_ID INTEGER PRIMARY KEY AUTOINCREMENT,USER VARCHAR(100) NOT NULL,PASS VARCHAR(100) NOT NULL,FIRST VARCHAR(100),LAST VARCHAR(100),AGE INTEGER,BIRTH DATE);");
        database.execSQL("CREATE TABLE IF NOT EXISTS COUNTRIES(COUNTRY_ID INTEGER PRIMARY KEY AUTOINCREMENT,COUNTRY_NAME VARCHAR(50) NOT NULL,CONTINENT VARCHAR(50) NOT NULL,CURRENCY_NAME VARCHAR(50) NOT NULL)");
        database.execSQL("CREATE TABLE IF NOT EXISTS DESCRIPTION(DESC_ID INTEGER PRIMARY KEY AUTOINCREMENT,CONTINENT VARCHAR(50) NOT NULL, DESCRIPTION VARCHAR(1000) NOT NULL,DESC_TSPOT VARCHAR(1000) NOT NULL)");
        database.execSQL("CREATE TABLE IF NOT EXISTS BUCKETLIST(BUCKET_ID INTEGER PRIMARY KEY AUTOINCREMENT, LISTING VARCHAR(50) NOT NULL, CONTINENT VARCHAR(50) NOT NULL);");
        database.execSQL("CREATE TABLE IF NOT EXISTS BUCKET_DATA(BUCKET_ID INTEGER PRIMARY KEY AUTOINCREMENT, LISTING VARCHAR(50) NOT NULL, USER VARCHAR(50) NOT NULL);");
        database.execSQL("INSERT INTO COUNTRIES(COUNTRY_NAME,CONTINENT,CURRENCY_NAME)VALUES('Beijing,China','ASIA','Chinese Yuan: '),('New Delhi, India','ASIA','Indian Rupee: '),('Jakarta, Indonesia','ASIA','Indonesian Rupiah: '),('Islamabad, Pakistan','ASIA','Pakistani Rupee: '),('Dhaka, Bangladesh','ASIA','Bangladeshi Taka: '),('Kuala Lumpur, Malaysia','ASIA','Malaysian Ringgit: '),('Tokyo, Japan','ASIA','Japanese Yen: '),('Bangkok, Thailand','ASIA','Thai Baht: '),('Seoul, South Korea','ASIA','South Korean Won: '),('Tehran, Iran','ASIA','Iranian Rial: ');");
        database.execSQL("INSERT INTO COUNTRIES(COUNTRY_NAME,CONTINENT,CURRENCY_NAME)VALUES('Moscow, Russia', 'EUROPE', 'Russian Ruble: '), ('Berlin, Germany', 'EUROPE', 'German Euro: '), ('Ankara, Turkey', 'EUROPE', 'Turkish Lira: '), ('London, United Kingdom', 'EUROPE', 'Pound: '), ('Paris, France', 'EUROPE', 'French Euro: '), ('Rome, Italy', 'EUROPE', 'Italian Euro: '), ('Madrid, Spain', 'EUROPE', 'Spanish Euro: '), ('Kyiv, Ukraine', 'EUROPE', 'Ukranian Hryvnia: '), ('Warsaw, Poland', 'EUROPE', 'Poland Zloty: '), ('Bucharest, Romania', 'EUROPE', 'Romanian Leu: ');");
        database.execSQL("INSERT INTO COUNTRIES(COUNTRY_NAME,CONTINENT,CURRENCY_NAME)VALUES('Washington DC, United States of America', 'NORTHA', 'US Dollar: '), ('Ottawa, Canada', 'NORTHA', 'Canadian Dollar: '), ('Mexico City, Mexico', 'NORTHA', 'Mexican Peso: '), ('Guatemala City, Guatemala', 'NORTHA','Guatemalan Quetzal: '), ('Havana, Cuba', 'NORTHA', 'Cuban Peso: '), ('Port-au-Prince', 'NORTHA', 'Haitan Gourde: '), ('Santo Domingo, Dominican Republic', 'NORTHA', 'Dominican Peso: '), ('Tegucigalpa, Honduras', 'NORTHA', 'Honduran Lempira: '), ('San Salvador, El Salvador', 'NORTHA', 'US Dollar: '),  ('Managua, Nicaragua', 'NORTHA', 'Nicaraguan Córdoba: ');");
        database.execSQL("INSERT INTO COUNTRIES(COUNTRY_NAME,CONTINENT,CURRENCY_NAME)VALUES('Abuja, Nigera','AFRICA','Nigerian Naira: '),('Addis Ababa, Ethiopia','AFRICA','Ethiopian Birr: '),('Cairo, Egypt','AFRICA','Egyptian Pound: '),('Kinshasa, Democratic Republic of Congo','AFRICA','Congoloese Franc: '),('Cape Town, South Africa','AFRICA','South African Rand: '),('Dodoma, Tanzania','AFRICA','Tanzanian Shilling: '),('Nairobi, Kenya','AFRICA','Kenyan Shilling: '),('Kampala, Uganda','AFRICA','Ugandan Shilling: '),('Algiers, Algeria','AFRICA','Algerian Diner: '),('Khartoum, Sudan','AFRICA','Sudanese Pound: ');");
        database.execSQL("INSERT INTO COUNTRIES(COUNTRY_NAME,CONTINENT,CURRENCY_NAME)VALUES('Buenos Aires, Argentina', 'SOUTHA', 'Argentina Peso: '), ('Sucre, Bolivia', 'SOUTHA', 'Bolivian Boliviano: '), ('Brasilia, Brazil', 'SOUTHA', 'Brazilian Real: '), ('Andean Condor, Chile', 'SOUTHA', 'Chilean Peso: '), ('Bogota, Columbia', 'SOUTHA', 'Colombian Peso'), ('Quito, Ecuador', 'SOUTHA', 'Ecuador US Dollar: '), ('Georgetown, Guyana', 'SOUTHA', 'Guyanese Dollar ; '), ('Asuncion, Paraguay', 'SOUTHA', 'Paraguay Garani: '), ('Lima, Peru', 'SOUTHA', 'Peruvian Sol: '), ('Paramaribo, Suriname', 'SOUTHA', 'Suriname Dollar: ');");
        database.execSQL("INSERT INTO COUNTRIES(COUNTRY_NAME,CONTINENT,CURRENCY_NAME)VALUES('Canberra, Australia', 'AUSTRALIA', 'Australian Dollar: '), ('Suva, Fiji', 'AUSTRALIA', 'Fijian Dollar: '), ('Tarawa, Kiribati',  'AUSTRALIA', 'Kiribati Dollar: '), ('Delap-Uliga-Djarrit, Marshall Islands',  'AUSTRALIA','Marshall US Dollar: '),  ('Palikir, Micronesia',  'AUSTRALIA','Micronesia US Dollar: '), ('Yaren, Nauru',  'AUSTRALIA', 'Australian Dollar: '), ('Wellington, New Zealand',  'AUSTRALIA','New Zealand Dollar: '), ('Ngerulmud, Palau',  'AUSTRALIA','Palau US Dollar: '), ('Port Moresby, Papau New Guinea',  'AUSTRALIA','Papau New Guinea Kina Dollar: '), ('Apia, Samoa', 'AUSTRALIA', 'Samoan tala: ');");
        database.execSQL("INSERT INTO DESCRIPTION(CONTINENT,DESCRIPTION,DESC_TSPOT)VALUES('ASIA','China is a country in East Asia and is the worlds most populous country, with a population of around 1.428 billion in 2017. Covering approximately 9,600,000 square kilometers, it is the third largest country by area and one of the earliest civilizations.','It was built to protect the north of the empire of China from enemy attacks. It is the longest structure humans have ever built.')," +
                "('ASIA','India is a country in South Asia. It is the seventh-largest country by area, the second-most populous country next to China. India remains one of the most ethnically diverse countries in the world and a leading hub for information technology services.','An immense mausoleum of white marble, built in Agra between 1631 and 1648 by order of the Mughal emperor Shah Jahan in memory of his favourite wife, the Taj Mahal is the jewel of Muslim art in India and one of the universally admired masterpieces of the worlds heritage.')," +
                "('ASIA','Indonesia is a transcontinental country in Southeast Asia and Oceania. The country has high levels of biodiversity and abundant natural resources. Indonesia consists of hundreds of distinct native ethnic and linguistic groups, with the largest one being the Javanese.','Borobudur is built of gray andesite stone. It rises to seven terraces, each smaller than the one below it. The top is the Great Stupa, standing 40 meters above the ground.')," +
                "('ASIA','Pakistan is a country in South Asia. With an ethic and linguistic diversity,Pakistan is the only country to have been created in the name of Islam.','This 160 kilometer long valley is most popular summer holiday spots for both Pakistanis as well as foreigners.')," +
                "('ASIA','Bangladesh is a secular, democratic and independent country in South Asia. Its large Muslim population makes Bangladesh the fourth largest Muslim-majority country in the world and home of its national animal, the Royal Bengal Tiger.','The construction was started in 1678 AD by Mughal Subahdar Muhammad Azam Shah who was son of Emperor Aurangzeb and later emperor himself.')," +
                "('ASIA','Malaysia is a Southeast Asian country occupying parts of the Malay Peninsula and the island of Borneo. Its known for its beaches, rainforests and mix of Malay, Chinese, Indian and European cultural influences. It is a founding member of ASEAN and APEC.','Now the worlds tallest twin structures, the 88-storey buildings were designed by Cesar Pelli & Associates with both towers joined at the 41st and 42nd floors (175m above street level) by a 58 metre-long, double-decker Sky Bridge.')," +
                "('ASIA','Philippines is a tropical country in Pacific Ocean, blessed with beautiful natural landscapes - and active volcanoes and extreme weather patterns. The Philippines, consisting of some 7,107 islands, is located in the western Pacific Ocean. Taiwan lies to its north, and Vietnam to the west.','With overall 45 islands located in Bacuit Bay, it gained a massive worldwide attention for its pristine white beaches, towering limestone cliffs, scenic mountains, mysterious caves, startling wildlife, enchanting lagoons and rich coral garden.')," +
                "('ASIA','Japan is an island country located in East Asia.The country is officially divided into 47 prefectures and traditionally into eight regions.Japan has been renowned for its comics,animation,video games and food.','It rises to 12,388 feet (3,776 metres) near the Pacific Ocean coast in Yamanashi and Shizuoka ken (prefectures) of central Honshu, about 60 miles (100 km) west of the Tokyo-Yokohama metropolitan area.')," +
                "('ASIA','Thailand is a Southeast Asian country. Its known for tropical beaches, opulent royal palaces, ancient ruins and ornate temples displaying figures of Buddha.The country encompasses diverse ecosystems, including the hilly forested areas of the northern frontier and the rugged coasts along the narrow southern peninsula.','It was built by Taksin of the short-lived Thonburi Kingdom (1768-1782), and named the Temple of Dawn to commemorate his passage by the site years earlier.')," +
                "('ASIA','South Korea is a country in East Asia, constituting the southern part of the Korean Peninsula and sharing a land border with North Korea. Since the 21st century the country is renowned for its influence in pop culture such as K-pop,K-drama and cinema.','Myeong-Dong is a dong in Jung-gu, Seoul, South Korea between Chungmu-ro, Eulji-ro, and Namdaemun-ro. It covers 0.99km² with a population of 3,409 and is mostly a commercial area, being one of Seouls main shopping, parade route and tourism districts.');");
        database.execSQL("INSERT INTO DESCRIPTION(CONTINENT,DESCRIPTION,DESC_TSPOT)VALUES('EUROPE','Russia is a European country located in Eastern Europe with a vast expanse of territory that stretches across Northern Asia. It is by far the largest country in the world by area, covering more than one-eighth of the Earths inhabited land area.','The square is considered the heart of Moscow since the citys major streets connect to major highways.')," +
                "('EUROPE','Germany is a country in Central and Western Europe and borders Denmark to the north, Poland and the Czech Republic to the east.With 83 million inhabitants, it is the second most populous state of Europe after Russia.','Built during the 18th century its was once the symbol that divided Germany to the east and west.')," +
                "('EUROPE','Turkey is a transcontinental country located mainly on the Anatolian peninsula in Western Asia, with a smaller portion on the Balkan peninsula in Southeastern Europe.Turkey was the home of the Ottoman Empire and was once a world power till the 18th century.','Built in 1609 the mosque is known as the Blue Mosque because of blue tiles surrounding the walls of interior design.')," +
                "('EUROPE','The United Kingdom is a sovereign country located off the north western coast of the European mainland. And consists of four constituent countries: England, Scotland, Wales and Northern Ireland. The UK remains a great power, with considerable economic, cultural, military, scientific and political influence internationally.','Finished in 1859 Big Ben is famous for its accuracy and for its massive bell.')," +
                "('EUROPE','France is a country whose territory consists of metropolitan France in Western Europe and several overseas regions and territories. The country is famed for its fashion houses, classical art museums and monuments like the Eiffel Tower.','Built on 1887 its famed as the Symbol of Love due to its superb construction and outstanding views.')," +
                "('EUROPE','Italy is a European country consisting of a peninsula delimited by the Alps and surrounded by several islands. The country has long been a global centre of art, music, literature, philosophy, science and technology, and fashion. And has greatly influenced and contributed to diverse fields including cinema, cuisine, sports,banking and business.','Built on 80 AD it was used for a variety of events and considered the greatest Roman architecture.')," +
                "('EUROPE','Spain is a country in Southwestern Europe with some pockets of Spanish territory across the Strait of Gibraltar and the Atlantic Ocean. With an area of 505,990 km2 (195,360 sq mi), Spain is the largest country in Southern Europe. Spain ruled one of the largest empires in history which was also one of the first global empires, leaving a large cultural and linguistic legacy.','Designed in 1882 it is famed for its innovative and artistic architecture.'),\n" +
                "('EUROPE','Ukraine is a country in Eastern Europe bordered by Russia to the north-east, Belarus to the north. Ukraine has an area of 603,628 km2 (233,062 sq mi),making it both the largest country entirely within Europe. The country is well known for its Orthodox churches, Black Sea coastline and forested mountains.','Founded in 1051 it is considered a symbol amongst Christians.')," +
                "('EUROPE','Poland is a country located in Central Europe divided into 16 administrative subdivisions, covering an area of 312,696 square kilometres. With a population of nearly 38.5 million people, Poland is the fifth most populous in Europe. Poland is a developed country, and a member state of the European Union, United Nations and G20.','Constructed in the 11th century it is known primarily for its grand historic architecture and cultural leadership.')," +
                "('EUROPE','Romania is a country located at the crossroads of Central, Eastern, and Southeastern Europe. It has been a member of the United Nations and member of the European Union. An overwhelming majority of the population identifies themselves as Eastern Orthodox Christians and are native speakers of Romanian.','Built in the 13th century the it is known as Draculas Castle because it serves as the home of Dracula.');");
        database.execSQL("INSERT INTO DESCRIPTION(CONTINENT,DESCRIPTION,DESC_TSPOT)VALUES('NORTHA','The U.S. is a country of 50 states covering a vast swath of North America, with Alaska in the northwest and Hawaii extending the nation’s presence into the Pacific Ocean.','Built in 1875 the Statue of Liberty remains an enduring symbol of freedom and democracy.')," +
                "('NORTHA','Canada is a country in the northern part of North America, and its ten provinces and three territories extend from the Atlantic to the Pacific and northward into the Arctic Ocean.','Niagara Falls is a geological wonder and one of the most famous waterfalls in the world.')," +
                "('NORTHA','Mexico is bordered to the north by the United States, to the south and west by the Pacific Ocean.Covering almost 2,000,000 square kilometers (770,000 sq mi).','The plaza is considered the birthplace of the Mexican Constitution.')," +
                "('NORTHA','Guatemala is a country in Central America bordered by Mexico to the north and west.The territory of modern Guatemala once formed the core of the Maya civilization, which extended across Mesoamerica.','Discovered in the 18th century, it was the prime city of the earliest civilization on earth.')," +
                "('NORTHA','Cuba is a country comprising the island of Cuba as well as Isla de la Juventud and several minor archipelagos. Cuba is a sovereign state and a founding member of the United Nations and its economy is dominated by the tourism industry.','Founded in 1519 it contains the core city of Havana and great architectural character.')," +
                "('NORTHA','Haiti is a country located on the island of Hispaniola in the Greater Antilles archipelago of the Caribbean Sea, to the east of Cuba and Jamaica and south of The Bahamas.The island was claimed by Spain and named La Española, forming part of the Spanish Empire until the early 17th century.','A port located in Haiti, is famed for its white beaches and high-end entertainment.')," +
                "('NORTHA','Dominican Republic is a country located on the island of Hispaniola in the Greater Antilles archipelago of the Caribbean region.The colony of Santo Domingo became the site of the first permanent European settlement in the Americas.','Bavarian Bavaro is known for its beautiful calm waters and crystalline white sands.')," +
                "('NORTHA','Honduras is a country in Central America and is bordered to the west by Guatemala, to the southwest by El Salvador.Honduras was home to several important Mesoamerican cultures, before the Spanish Colonization in the sixteenth century.Honduras is known for its rich natural resources','The largest of the Bay Islands of Honduras is known for scuba diving.')," +
                "('NORTHA','El Salvador is the smallest and the most densely populated country in Central America and is bordered on the northeast by Honduras, on the northwest by Guatemala.El Salvador was for centuries inhabited by several Mesoamerican nations.','Constructed in 1853 it is famed as the icon of Suchitoto.')," +
                "('NORTHA','Nicaragua is bordered by Honduras to the northwest, the Caribbean to the east, Costa Rica to the south, and the Pacific Ocean to the southwest. The multi-ethnic population of six million includes people of indigenous, European, African, and Asian heritage.','The islands are the main tourist attraction on the Atlantic coast of Nicaragua.');");
        database.execSQL("INSERT INTO DESCRIPTION(CONTINENT,DESCRIPTION,DESC_TSPOT)VALUES('AFRICA','Nigeria is a country in West Africa, bordering Niger in the north, Chad in the northeast, Cameroon in the east. Nigeria has been home to a number of ancient and indigenous kingdoms and states over the millennia. And has often referred to as the Giant of Africa, owing to its large population and economy.','Served as a fortress in the 19th century Olumo Rock is annually celebrated with lots of sacrifices.')," +
                "('AFRICA','Ethiopia is a landlocked country in the Horn of Africa and shares borders with Eritrea to the north, Djibouti to the northeast. It is widely considered as the region from which modern humans first set out for the Middle East and places beyond. The nation is a land of natural contrasts, with its vast fertile west, its forests and its numerous rivers.','It is known as Tis Abay in Amharic, meaning great smoke and is considered one of Ethiopias best known tourist attractions.')," +
                "('AFRICA','Egypt is a country spanning the northeast corner of Africa and southwest corner of Asia by a land bridge formed by the Sinai Peninsula. Egypt has one of the longest histories of any country,considered a cradle of civilisation it pioneered on writing, agriculture and urbanisation. With over 95 million inhabitants, Egypt is the most populous country in North Africa.','Built on 2589 BCE, it is a defining symbol of Egypt and the last of the ancient Seven Wonders of the World.')," +
                "('AFRICA','The Congo by area the largest country in sub-Saharan Africa and the second-largest in all of Africa. Congo is rich in natural resources. It boasts vast deposits of industrial diamonds, cobalt, and copper; one of the largest forest reserves in Africa. And about half of the hydroelectric potential of the continent.','Founded on 1883 it constitutes the financial and administrative centre of the country.')," +
                "('AFRICA','South Africa is the southernmost country in Africa and is bounded to the coastline of Southern Africa stretching along the South Atlantic and Indian Oceans. The country is renowned for its varied topography, great natural beauty, and cultural diversity, all of which have made the country a favoured destination for travelers.','Nicknamed the Mother City Cape Town is the oldest city in South Africa spanning more than 300 years.')," +
                "('AFRICA','Tanzania is a country in East Africa within the African Great Lakes region. Over 100 different languages are spoken in Tanzania, making it the most linguistically diverse country in East Africa. The country is known for its vast wilderness areas and its iconic mountain Mt Kilimanjaro.','Mount Kilimanjaro is the African continents highest mountain and famed for its snow capped peak.')," +
                "('AFRICA','Kenya is a country in East Africa famed for its scenic landscapes and vast wildlife preserves. The country’s diverse wildlife and panoramic geography draw large numbers of European and North American visitors, and tourism is an important contributor to Kenyas economy.','Hells Gate National Park a park is famous for its geothermal station, Lower Gorge and spectacular sceneries.')," +
                "('AFRICA','Uganda is a landlocked country in East-Central Africa bordered to the east by Kenya, to the north by South Sudan. Its rich fertile land became a mainstay of the agricultural economy and a favourite of connoisseurs around the world. Uganda is populated by dozens of ethnic groups the English language and Christianity help unite these diverse peoples.','The park is known for its beautiful and diverse plant life.')," +
                "('AFRICA','Algeria is a country in the Maghreb region of North Africa and is a large, predominantly Muslim country. It was once a colony of France and modernized agriculture and the economy. And has one of the largest economies on the continent, based largely on energy exports and oil.','Opened in 1982, it was to commemorate the independence of Algeria.')," +
                "('AFRICA','Sudan is a country in northeastern Africa and is bordered by Egypt to the north, Libya to the northwest. The country occupies 1,886,068 square kilometres (728,215 square miles), making it Africas third-largest country. Since ancient times the Sudan region has been an arena for interaction between the cultural traditions of Africa and those of the Mediterranean world.','During the 13th century BCE  it was the site of an almost universal religion.');");
        database.execSQL("INSERT INTO DESCRIPTION(CONTINENT,DESCRIPTION,DESC_TSPOT)VALUES('SOUTHA','Argentina is a country located mostly in the southern half of South America. With a mainland area of 2,780,400 km2 (1,073,500 sq mi),Argentina is the eighth-largest country in the world. It is the largest Spanish-speaking nation in South America.','The glacier descends from the Southern Patagonian Icefield (image top)—2100 meters elevation (6825 feet) in the Andes Mountains—down into the water and warmer altitudes of Lago Argentino at 180 meters above sea level.')," +
                "('SOUTHA','Bolivia is a landlocked country located in western-central South America. Although only one-third of its territory lies in the Andes Mountains. Bolivia is traditionally regarded as a highland country where the largest cities are located.','Known as \"Death Road\" for all of the reasons youd guess. Driving up or down this 43-mile (69-kilometer) switchback is extremely perilous due to fog, landslides, cascades, and cliffs that drop 2,000 feet (610 meters) at every turn.')," +
                "('SOUTHA','Brazil is the largest country in both South America and Latin America. At 8.5 million square kilometers and with over 211 million people. Brazil is the worlds fifth-largest country by area and the sixth most populous.','The statue weighs approximately 635 tonnes. Christ the Redeemer is located in the Tijuca Forest National Forest, at the top of the Corcovado Mountain.')," +
                "('SOUTHA','Chile is a South American country occupying a long, narrow strip of land between the Andes to the east and the Pacific Ocean to the west. Chile is among South Americas most economically and socially stable and prosperous nations, with a high-income economy and high living standards.','Valle de la Luna (which translates to \"valley of the moon\") is situated in the Atacama, one of the worlds driest deserts, which stretches for 600 miles from northern Chile into southern Peru.')," +
                "('SOUTHA','Colombia is a country largely situated in the north of South America, with land and territories in North America. Colombia has the second-highest biodiversity in the world and is one of the worlds 17 megadiverse countries. Its territory encompasses the Amazon rainforest.','These are the remains of a city built in around 800AD, some 650 years before Perus Machu Picchu.')," +
                "('SOUTHA','Ecuador is a country straddling the equator on South Americas west coast. A territory that was colonized by Spain during the 16th century,most of its inhabitants have Spanish descent. Therefore making Spanish the official language and is spoken by a majority of the population.','Cotopaxi is a stratovolcano that has erupted 50 times since 1738. The 1877 eruption melted snow and ice on the summit, which produced mudflows that traveled 60 miles (100 km) from the volcano.')," +
                "('SOUTHA','Guyana is a country on the northern mainland of South America. It is also the only English speaking country in South America. The countrys chief economic assets have been its natural resources, mainly its pristine rainforests, sugarcane plantations, rice fields, and gold reserves.','Located on the Potaro River in the Kaieteur National Park, it sits in a section of the Amazon rainforest included in the Potaro-Siparuni region of Guyana.')," +
                "('SOUTHA','Paraguay a landlocked country in south-central South America. The Paraguayans are known for being a very happy and easy-living people and many times the country has topped the worlds happiest place charts because of the positive experiences lived and expressed by the population.','This was in the period when Spain was still fighting for control of South American soil. The fight then was against the natives and by the time the Jesuits arrived many of the physical battles were in the past but the battle for ideological power was still at its peak.')," +
                "('SOUTHA','Peru is a country in western South America. It has great diversity of climate, of way of life, and of economic activity is brought about by the extremes of elevation and by the southwest winds that sweep in across the cold Peru Current. And was home to the earliest civilization, the Inca Empire.','Machu Picchu is a 15th-century Inca site located on a ridge between the Huayna Picchu and Machu Picchu mountains in Peru.')," +
                "('SOUTHA','Suriname is a country on the northeastern Atlantic coast of South America. It is one of the smallest countries in South America, yet its population is one of the most ethnically diverse in the region and the world.','The temple attracts many visitors, both Hindus and non-Hindus, coming from Suriname and from all over the world.');");
        database.execSQL("INSERT INTO DESCRIPTION(CONTINENT,DESCRIPTION,DESC_TSPOT)VALUES('AUSTRALIA','Australia is a sovereign country comprising the mainland of the Australian continent,and numerous smaller islands. A megadiverse country, its size gives it a wide variety of landscapes, with deserts in the centre, tropical rainforests in the north-east, and mountain ranges in the south-east.','Known as a \"land iceberg\" it is one of Australias most recognisable natural landmarks.')," +
                "('AUSTRALIA','Fiji is an island country in Melanesia, part of Oceania in the South Pacific Ocean. The majority of Fijis islands formed through volcanic activity starting around 150 million years ago. It has one of the most developed economies in the Pacific due to abundant forest, mineral, and fish resources.','Nicknamed as Castaway Island the island resort is used for holidays and vacations,')," +
                "('AUSTRALIA','Kiribati is a country in the central Pacific Ocean. The state comprises 32 atolls and are dispersed over 3.5 million square kilometres (1.3 million square miles). Kiribati is the only country in the world to be situated in all four hemispheres.','This tiny, sparsely populated island offers fine sand beaches & a turquoise color of thesea.')," +
                "('AUSTRALIA','Marshall Islands is an island country and a United States associated state near the equator in the Pacific Ocean. The islands in the archipelago were first explored by Europeans in the 1520s, and was named after John Marshall who visited in 1788.','One of the most popular atolls to visit its known for its white-sand beaches and waters with abundant marine life.')," +
                "('AUSTRALIA','Micronesia is a subregion of Oceania, composed of thousands of small islands in the western Pacific Ocean. Micronesia is made up of 4 island states: Pohnpei, Kosrae, Chuuk and Yap.  The country is known for palm-shaded beaches, wreck-filled dives and ancient ruins.','One of the most photographed waterfall it is Micronesias iconic natural landmarks.')," +
                "('AUSTRALIA','Nauru is an island country in Micronesia, a subregion of Oceania, in the Central Pacific. Nauru is a phosphate-rock island with rich deposits near the surface, which allowed easy strip mining operations. Additionally, its population of 10,670 is the worlds third smallest, after Vatican City and Tuvalu.','Anibare Bay was formed by the underwater collapse of the east side of the volcano that underlies Nauru.')," +
                "('AUSTRALIA','New Zealand is a sovereign island country in the southwestern Pacific Ocean. The country has two main landmasses the North Island, and the South Island. New Zealand became a colony within the British Empire and majority of its inhabitants today are from European Descent.','It was named in recognition of its sheer rock faces, majestic peaks and geographic features.')," +
                "('AUSTRALIA','Palau is an archipelago of over 340 islands, part of the Micronesia region in the western Pacific Ocean. The countrys two official languages are Palauan and English,though Japanese and other languages serves as regional languages.','A small collection of coral uprises is unique due to its island formation.')," +
                "('AUSTRALIA','Papau New Guinea a country in the southwestern Pacific, encompasses the eastern half of New Guinea and its offshore islands. A country of immense cultural and biological diversity, it’s known for its beaches and coral reefs.','Mt Wilhelm is the highest and challenging peak in Papua New Guinea due to its rocky slope and terrain.')," +
                "('AUSTRALIA','Samoa is a country consisting of two main islands, Savaii and Upolu, and four smaller islands. Samoan culture is undoubtedly central to Polynesian life, and its styles of music, dance, and visual art have gained renown throughout the Pacific islands and the world.','Formed by a massive basaltic shield volcano which rises from the seafloor of the western Pacific Ocean.');");
        database.execSQL("INSERT INTO BUCKETLIST(LISTING,CONTINENT)VALUES('Bali', 'Asia'), ('Maldives', 'Asia'), ('Ngapali', 'Asia'), ('Mount Fuji', 'Asia'), ('Koh Samet', 'Asia'), ('Boracay', 'Asia'), ('Seoul', 'Asia'), ('Hong Kong','Asia'), ('Singapore', 'Asia'), ('Bangkok', 'Asia');");
        database.execSQL("INSERT INTO BUCKETLIST(LISTING,CONTINENT)VALUES('Paris', 'Europe'), ('Florence', 'Europe'), ('Santorini', 'Europe'), ('Amsterdam', 'Europe'), ('London', 'Europe'), ('Barcelona', 'Europe'), ('Rome', 'Europe'), ('Reykjavik', 'Europe'), ('Edinburgh', 'Europe'), ('Prague', 'Europe');");
        database.execSQL("INSERT INTO BUCKETLIST(LISTING,CONTINENT)VALUES('Grand Canyon', 'North America'), ('Yucatan Peninsula', 'North America'), ('New York', 'North America'), ('Banff', 'North America'),  ('Las Vegas', 'North America'), ('San Francisco', 'North America'), ('Mexico City', 'North America'), ('New Orleans', 'North America'), ('Hawaiian Islands', 'North America'), ('Northern Lights', 'North America');");
        database.execSQL("INSERT INTO BUCKETLIST(LISTING,CONTINENT)VALUES('Madagascar', 'Africa'), ('Cairo', 'Africa'), ('Cape Town', 'Africa'), ('Luxor', 'Africa'), ('Casablanca', 'Africa'), ('Johannesburg', 'Africa'), ('Maasai Mara', 'Africa'), ('Seychelles', 'Africa'), ('Okavango Delta', 'Africa'), ('Tenerife', 'Africa');");
        database.execSQL("INSERT INTO BUCKETLIST(LISTING,CONTINENT)VALUES('Peru', 'South America'), ('Iguazu Falls', 'South America'), ('Lake Titicaca', 'South America'), ('Machu Picchu', 'South America'), ('Amazon', 'South America'), ('Angel Falls', 'South America'), ('Easter Island', 'South America'), ('Cusco', 'South America'), ('Huacachina', 'South America'), ('Asuncion', 'South America'); ");
        database.execSQL("INSERT INTO BUCKETLIST(LISTING,CONTINENT)VALUES('Opera House','Australia'), ('Queensland', 'Australia'), ('Ayers Rock', 'Australia'), ('Harbour Bridge', 'Australia'),('Whitsunday Islands', 'Australia'),('Fraser Island', 'Australia'),('Bondi Beach', 'Australia'),('Crandle Mountain', 'Australia'),('Cable Beach', 'Australia'),('Daintree Rainforest','Australia');");
        User = (EditText) findViewById(R.id.User);
        Pass = (EditText) findViewById(R.id.Pass);
        Login = (Button) findViewById(R.id.Login);
    }
    public void signin(View v){
        intent = new Intent(MainActivity.this, Menu.class);
        user = User.getText().toString().trim();
        pass = Pass.getText().toString().trim();
        Cursor c = database.rawQuery("SELECT * FROM USER_INFO WHERE USER IN ('"+user+"') and PASS IN ('"+pass+"');",null);
        if(c.getCount()==0){
            Toast.makeText(this, "Username or password incorrect...", Toast.LENGTH_SHORT).show();
            return;
        } else {
            StringBuffer buff = new StringBuffer();
            while(c.moveToNext()) {
                buff.append(c.getString(3));
                first = buff.toString();
                buff = new StringBuffer();
                buff.append(c.getString(4));
                last = buff.toString();
                buff = new StringBuffer();
                buff.append(c.getString(5));
                age = buff.toString();
                buff = new StringBuffer();
                buff.append(c.getString(6));
                birth = buff.toString();
            }
            c.close();
            database.close();
            Login.setClickable(false);
            Toast.makeText(this, (""+first+last+age+birth+""), Toast.LENGTH_SHORT).show();
            startActivity(intent);
        }
    }
    public void singup(View v){
        intent = new Intent(MainActivity.this, SignUp.class);
        startActivity(intent);
    }
}
